### ISSUE TITLE
Error in login

### ISSUE THREAD

**Issue by Phasmod** [dante4rt/paramgaming-bot#2]
![Screenshot_20240404-095519](https://github.com/dante4rt/paramgaming-bot/assets/65063958/8b14dd0e-25fd-4eb3-8374-0e78d601f2f0)

**Comment by darknessus** [comment]
still has this error

**Comment by dante4rt** [comment]
> ![Screenshot_20240404-095519](https://private-user-images.githubusercontent.com/65063958/319518064-8b14dd0e-25fd-4eb3-8374-0e78d601f2f0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjM2NzYsIm5iZiI6MTcxMzEyMzM3NiwicGF0aCI6Ii82NTA2Mzk1OC8zMTk1MTgwNjQtOGIxNGRkMGUtMjVmZC00ZWIzLTgzNzQtMGU3OGQ2MDFmMmYwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE5MzYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2OThmYTM5YTBlOWVhMTdmYjg3MmIwYjhjNzgxMjk4MDQyNGFiYzMwYjVlZWRmOWRmNTdhY2QxZWZmODFjMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rt11zPDFYIdW4YAHKuO7ZgDlYlSlRTDM49qw0gLyl1Q)



> still has this error

Use my snippet:
https://github.com/dante4rt/paramgaming-bot/blob/main/snippet.js

**Comment by Phasmod** [comment]
Well actually I found a way on how it works most time I on VPN and itll work and I'm using this medium to appreciate all what you've been doing ser in terms of all those automation stuff really appreciate. Thanks ser

**Comment by dante4rt** [comment]
> Well actually I found a way on how it works most time I on VPN and itll work and I'm using this medium to appreciate all what you've been doing ser in terms of all those automation stuff really appreciate. Thanks ser

Anytime, bro!
